### PR TITLE
calendar enhanced

### PR DESCRIPTION
**Pull request by amanBhawsar**
darkMode
lightMode

### CODE REVIEW

**Review by vinitraj10 — CHANGES_REQUESTED** [review]
@amanBhawsar  can you try to align dates consistently,like in you attached screenshot,the last row of dates is centered align,but it should start from the left corner,like a usual calendar

**Review by vinitraj10 — CHANGES_REQUESTED** [review]
Also, can you just remove the `CONFIRM DATE` Button from the calendar completely and move out that completely from calendar component,we can use that space as a dynamic children,so that what every being passed from parent,we will show there,else it would be null.

**Comment by amanBhawsar** [comment]
> @amanBhawsar can you try to align dates consistently,like in you attached screenshot,the last row of dates is centered align,but it should start from the left corner,like a usual calendar

fixed - Dates of last row is also left aligned now

**Comment by amanBhawsar** [comment]
> Also, can you just remove the `CONFIRM DATE` Button from the calendar completely and move out that completely from calendar component,we can use that space as a dynamic children,so that what every being passed from parent,we will show there,else it would be null.

Yes, then component can be used with other options like Ok and Cancel buttons or none as per the need. Component is more reusable now.

**Review by vinitraj10 — APPROVED** [review]

**Pull request merged**
