### PR TITLE
InfoBox component

### PR DESCRIPTION
**Pull request by rushatgabhane**
Implemented everything based on feedback provided, expect functional component support for icons.
I think you can pick this up from here, use it as a base.
### Props
```
export interface InfoBoxProps {
  label: string;
  backgroundColor: 'info' | 'success' | 'warning' | 'error' | 'transparent';
  icon: boolean | string;
  borderColor?: 'info' | 'success' | 'warning' | 'error';
  style?: StyleType;
  textStyle?: StyleType;
}
``` 
### Icon prop
Default icon: *react-native-vector-icons/AntDesign* **exclamationcircle**
An icon name can be passed to set custom icon, present in AntDesign. eg: `icon="github"`
I couldn't add support for functional component, to use images as icons.

New Project

### CODE REVIEW

**Comment by vinitraj10** [comment]
Hey, @rushatgabhane  thanks for this PR, we will go through this let you know our feedbacks, meanwhile, we are also working on the branching strategy for this project, so you might need to change the PR to a different branch, we will add a better-contributing doc for this repo.

Also we are planning a frontatish release very soon,we will come with the release plans too,if your PR gets reviewed we will release this component in that release and let u know for sure!!

Thanks

**Review by vinitraj10 — CHANGES_REQUESTED** [review]
@rushatgabhane  we would need the documentation too for this component,so kindly go through the other docs too and create one for this too

**Review by amanBhawsar — APPROVED** [review]

**Comment by rushatgabhane** [comment]
Yeah sure, thanks!
The docs have been added.

**Review by vinitraj10 — APPROVED** [review]

**Comment by vinitraj10** [comment]
Merging this PR @rushatgabhane, we will let you know once we start using it. once again thanks for your effort we look forward to more such contributions. FYI we will take this for `0.4.1` release that is why your PR has been changed to it

cc- @amanBhawsar @john1jan

**Pull request merged**
